### ISSUE TITLE
Button detection doesn't work using EB==0

### ISSUE THREAD

**Issue by pleserwolf** [alexsporn/homebridge-enocean#1]
Hi Alex,

your plugin is exactly what I've been looking for! I couldn't get my FTM215 to work and have found out the following:

Using R1 to detect which button has been pressed only works when EB==1 (pressed event), not when EB==0 (released event). R1 is always 0 when EB==0. 

I made a very small adjustment and it seems to work for me now:
- Ignore the released event altogether (It seems the pressed event triggers button rules in HomeKit);
- Look for the pressed event as a trigger for setSwitchEventValue.

(Code changes are in my fork)

Best,

Philipp

**Comment by krukje** [comment]
I'm trying to get this plugin to work but to no avail. Do you run HomeBridge on Raspberry Pi / Raspbian by any chance? 
Would like to try out your fork, how can I get it to work in HomeBridge?

**Comment by pleserwolf** [comment]
I had my homebridge instance running on an RPI for quite a while, so it should work! I have not pushed my fork to NPM yet, so you would have to clone the fork locally from GitHub and run "npm install" or the global version, depending on your setup. You should be able to use it in your homebridge config after that.

**Comment by krukje** [comment]
Thanks for you help. I removed homebridge-enocean, cloned yours to my RPi and tried 'sudo npm install' but I get errors, relating to serial port issues it seems.

```
gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/12.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/homebridge/homebridge-enocean/node_modules/@serialport/bindings/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/homebridge/homebridge-enocean/node_modules/@serialport/bindings/.node-gyp'
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/homebridge/homebridge-enocean/node_modules/@serialport/bindings
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
I've also tried to run npm install serialport and npm install raspi-serial but I get errors that way too

**Comment by pleserwolf** [comment]
That’s a permission problem with a dependency. You might want to try —unsafe-perm with your npm call. 


On Mon, Apr 13, 2020, at 18:25, jeroen020 wrote:
> 

> Thanks for you help. I removed homebridge-enocean, cloned yours to my RPi and tried 'sudo npm install' but I get errors, relating to serial port issues it seems.

> `gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/12.16.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/homebridge/homebridge-enocean/node_modules/@serialport/bindings/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/homebridge/homebridge-enocean/node_modules/@serialport/bindings/.node-gyp'
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/homebridge/homebridge-enocean/node_modules/@serialport/bindings
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@8.0.7 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@8.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

`

**Comment by krukje** [comment]
Thanks for your quick reply. It was weird, first time I tried adding --unsafe-perm I got errors, but just did it again and it now it looks like it has actually installed, no more errors.

Next stumbling block is how to make the plugin appear in HomeBridge - when I select 'Plugins' in the web interface, it only shows the default Homebridge Config UI X. I unpacked the zip in /home/homebridge/homebridge-enocean and added code to the config, but as the plugin is not registered, it gives errors. How do I make your plugin appear in the Homebridge web interface?

**Comment by pleserwolf** [comment]
The example config file in the repo was not up to date. I just commited a version that should work.

You don't have to register plugins with homebridge as a separate step. Just use the platform in the config file and make sure that the plugin is installed in the npm repo that homebridge uses.

**Comment by krukje** [comment]
Yay, I've got it running! The install command that did it in the end was:

`pi@raspberrypi:/home/homebridge $ sudo npm install -g https://github.com/zonefuenf/homebridge-enocean.git --unsafe-perm`

Thanks so much for your help and patience, I now have a use for all those spare EnOcean switches!

**Comment by krukje** [comment]
Did some more testing, I get about 2 floors reach, which is not bad. However I noticed the plugin crashed after a while, with the following error:

```
[4/14/2020, 3:40:53 PM] [EnOcean] fef4c1d0 RPi2: Button A0 pressed
[4/14/2020, 3:41:08 PM] [EnOcean] fef4c1d0 RPi2: Button AI pressed
[4/14/2020, 3:41:08 PM] [EnOcean] fef4c1d0 RPi2: Button AI pressed
[4/14/2020, 3:41:09 PM] [EnOcean] fef4c1d0 RPi2: Button AI pressed
[4/14/2020, 3:41:53 PM] [EnOcean] Unknown sender fef4d1d0
(node:23238) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'services' of undefined
    at EnoceanPlatform.setSwitchEventValue (/usr/lib/node_modules/homebridge-enocean-zonefuenf/index.js:61:21)
    at Enocean.<anonymous> (/usr/lib/node_modules/homebridge-enocean-zonefuenf/index.js:43:19)
    at Enocean.emit (events.js:311:20)
    at Enocean.EventEmitter.emit (domain.js:482:12)
    at ESP3Transformer.<anonymous> (/usr/lib/node_modules/homebridge-enocean-zonefuenf/Enocean.js:52:25)
    at ESP3Transformer.emit (events.js:311:20)
    at ESP3Transformer.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at ESP3Transformer.Readable.push (_stream_readable.js:209:10)
(node:23238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
When I restart HomeBridge it works as expected again.

Also, more of a warning, I see this message in the log:

`[4/14/2020, 3:45:36 PM] [Config] [homebridge-enocean-zonefuenf] Failed to check registry.npmjs.org for updates: Request failed with status code 404`

Edit: I managed to get it up and running on my production Raspberry Pi 4 in a simpler way
`npm install -g zonefuenf/homebridge-enocean`

I did have to first set the permissions right so the pi user could write to the node_modules:
`pi@raspberrypi:/dev $ sudo chown -R $USER /usr/lib/node_modules/`

**Comment by pleserwolf** [comment]
Thanks for the feedback. There seems to be a bug when a new sender is detected without having been configured first.

The npm error in the log is caused by me not having properly published the package to the repo. I was going to do that anyway, because it makes updating a lot easier.

**Comment by krukje** [comment]
Thanks @zonefuenf, that explains it. To cover my home I now have two raspberry's configured for Enocean so it sounds like I have to configure each switch in both Homebridge instances, otherwise it would crash the one it's not configured for. So if this bug could be fixed that would be great, is there any chance that'll happen? I'm planning to add a bunch of Enocean switches so would be good to know.

**Comment by pleserwolf** [comment]
The NPM problem should be solved by now, I uploaded a release to the repo. I'm going to look into the other problem, as I agree that it's pretty serious. I can't promise a timeline, though.

**Comment by pleserwolf** [comment]
@jeroen020, I have published version 0.3.0, which should take care of your problem. I am going to close this issue for now. All code, documentation and issue tracking for my fork is at https://github.com/zonefuenf/homebridge-enocean-zonefuenf

**Comment by krukje** [comment]
Hero! Just tested it and it works. You've just made my weekend!

**Comment by alexsporn** [comment]
Sorry I haven’t taken a look at this, been busy with other projects and moved from homebridge to homeassistant for all of my home automation

**Comment by pleserwolf** [comment]
That’s fine! I have solved my problem and added a few little things here and there in my fork. Thanks for starting this, it’s really useful.
